# Minecraft properties
minecraft_version = 1.20.1
minecraft_java_version = 17

# Common
architectury_plugin_version = 3.4-SNAPSHOT
architectury_loom_path = dev.architectury.loom:dev.architectury.loom.gradle.plugin
architectury_loom_id = dev.architectury.loom
architectury_loom_version = 1.11-SNAPSHOT

supported_loaders = fabric,forge

# Fabric
fabric_loader_version = 0.17.2

# Forge
forge_version = 1.20.1-47.4.10
forge_loader_version = [47,)

# Mods
common_cloth_config_version = 11.1.136

fabric_api_version = 0.92.9+1.20.1
fabric_mod_menu_version = 7.2.2
