# Minecraft properties
minecraft_version = 1.21.2
minecraft_java_version = 21

# Common
architectury_plugin_version = 3.4-SNAPSHOT
architectury_loom_path = dev.architectury.loom:dev.architectury.loom.gradle.plugin
architectury_loom_id = dev.architectury.loom
architectury_loom_version = 1.11-SNAPSHOT

supported_loaders = fabric,forge,neoforge

# Fabric
fabric_loader_version = 0.17.2

# Forge
forge_version = 1.21.1-52.1.0
forge_loader_version = [52,)

# NeoForge
neoforge_version = 21.2.1-beta
neoforge_loader_version = [1,)
neoforge_toml_name = META-INF/neoforge.mods.toml

# Mods
common_cloth_config_version = 17.0.144

fabric_api_version = 0.106.1+1.21.2
fabric_mod_menu_version = 12.0.1
