modLoader = "javafml"
loaderVersion = "${neoforge_loader_version}"
license = "${mod_license}"

[[mods]]
modId = "plaguesnoisycreepers"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_author}"
description = '''
${mod_desc}
'''
logoFile = "icon.png"

[[dependencies.plaguesnoisycreepers]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_loader_version}"
ordering = "NONE"
side = "BOTH"

[[dependencies.plaguesnoisycreepers]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "plaguesnoisycreepers.mixins.json"
